### ISSUE TITLE
Allow `--no-` in option declaration

### ISSUE THREAD

**Issue by oganexon** [c4spar/deno-cliffy#102]
Currently, it's not possible to create options such as `--no-check`.
I would like to be able to declare this option because the `--check` option doesn't make sense in my case.

```ts
import { Command } from "https://x.nest.land/cliffy@0.14.3/command/mod.ts";

new Command()
  .option("--no-check", "desc")
  .action(() => {})
  .parse();
```

```sh
> deno run -A --unstable foo.ts
  [...]
  Error: Unknown option: --no-check
```

**Comment by c4spar** [comment]
Hi @oganexon,

i have added improved support for negatable options in cliffy v0.15.0. It should be possible to add a `--no-check` option now.
In the readme is an example for negatable options: https://github.com/c4spar/deno-cliffy/tree/master/command#negatable-options

**Comment by oganexon** [comment]
Awesome 🚀
