### ISSUE TITLE
iTerm2 cursor hidden after exiting with ctrl+c

### ISSUE THREAD

**Issue by marcushultman** [c4spar/deno-cliffy#108]

**Comment by c4spar** [comment]
Hey @marcushultman,

can you please add an example how i can reproduce this? I have checked all prompts and the cursor is always visible after hitting ctrl+c.
And which operating system do you use?

**Comment by marcushultman** [comment]
@c4spar turns out this was due to the changes in https://github.com/c4spar/deno-cliffy/pull/106

**Comment by c4spar** [comment]
All right, np! 😉
