### ISSUE TITLE
Broken special character encoding on Windows Terminal

### ISSUE THREAD

**Issue by prcdpr** [c4spar/deno-cliffy#113]
Windows Terminal supports emoji:

```powershell
deno run https://deno.land/std/examples/welcome.ts
```
![image](https://user-images.githubusercontent.com/43776797/99917143-bc7c8000-2d0e-11eb-8276-a557cc03b76b.png)

However, cliffy Prompt with emoji prints garbled output instead

```typescript
import { Input } from "https://deno.land/x/cliffy/prompt/mod.ts";
const name: string = await Input.prompt( {message: `What's your name?`, pointer: '🦕' } );
```

```
deno run --unstable https://gist.githubusercontent.com/prcdpr/a202eabe338fc47bcc5e1c80b987f974/raw/39ac37c59ad0efc8bb7b03b02225e7eaafde5bd7/cliffy-prompt-emoji.ts
```

![image](https://user-images.githubusercontent.com/43776797/99917256-5e9c6800-2d0f-11eb-9743-9ecddd6c4445.png)

Code gist to test can be found here https://gist.github.com/prcdpr/a202eabe338fc47bcc5e1c80b987f974

**Comment by c4spar** [comment]
Hi @prcdpr,
found the solution here https://github.com/denoland/deno/issues/6131#issuecomment-640032166
you have to enable utf8 character encoding in windows than it should work.

**Comment by prcdpr** [comment]
Thanks for finding this. I don't like the solution mentioned as it requires system restart, but following can also be done (copying my another answer):

```powershell
[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8
```

To keep this setting persistent, you can create a `%userprofile%/Documents/PowerShell/profile.ps1` with the line above.

**Comment by c4spar** [comment]
Reopening because this is still an issue.

**Comment by c4spar** [comment]
Looks like this is now fixed.
