### ISSUE TITLE
Add auto-complete prompt

### ISSUE THREAD

**Issue by quilicicf** [c4spar/deno-cliffy#116]
Hi, 

Cliffy prompts look pretty dope but one of the most useful prompts IMO would be the auto-complete prompt ([example](https://www.npmjs.com/package/enquirer#autocomplete-prompt)).

Would you consider adding it?

> I tried to port enquirer to Deno (see [PR 316](https://github.com/enquirer/enquirer/pull/316)) but the discrepancies in the key events APIs make it pretty tough and the maintainer couldn't get a look so I'm stuck. I'm thinking that it may be a better option to have a new strong prompt lib in Deno rather than porting a NodeJS lib with all the complexity it adds (my PR was huge).

**Comment by c4spar** [comment]
Hi @quilicicf, thanks for your feedback!

yes autocompletion support is definitly on my list. My plan was to add native autocompletion support to the GenericInput class. So all pormpts which inherits from it like `Input`, `Number`, `List` and `Confirm` gets autocompletion support.

**Comment by quilicicf** [comment]
That would be awesome thanks!

**Comment by quilicicf** [comment]
Thanks a bunch! 
Will try this :tada:

**Comment by quilicicf** [comment]
Just tried it out, it works like a charm :-) 
I noticed it's not in a release yet though, I tried it using GitHub as a CDN.
 Would be super nice to have a release with it when it makes sense. 
 Thanks a lot :pray:

**Comment by c4spar** [comment]
Hi @quilicicf, thx for your feedback!
Sry, but i had not so much time in the last days. I will try to make a new release today or tomorrow. But i want to finish some other things first.

**Comment by quilicicf** [comment]
Don't worry, there's no rush!
Real life first :-)

**Comment by c4spar** [comment]
Hi @quilicicf,
it's now available in v0.17.0.

**Comment by quilicicf** [comment]
Thanks! :+1:
