### ISSUE TITLE
Cliffy breaks on Deno 1.6

### ISSUE THREAD

**Issue by maximousblk** [c4spar/deno-cliffy#121]
screenshot:

![image](https://user-images.githubusercontent.com/28438021/101616961-061ad980-3a36-11eb-8d39-9182096e0865.png)

**Comment by c4spar** [comment]
Hi @maximousblk,

thx for the issue. It should be already fixed in the master branch. I will make a new release after work.

**Comment by c4spar** [comment]
@maximousblk v0.16.0 is released now and the issue should be fixed.
