### ISSUE TITLE
TS1243 [ERROR]: 'async' modifier cannot be used with 'abstract' modifier.

### ISSUE THREAD

**Issue by danjrauch** [c4spar/deno-cliffy#125]
It seems that the recent move to Typescript 4.1 by the Deno has caused this error in library code to appear. 

This is the error text I get trying to run a project using cliffy: 

```
error: TS1243 [ERROR]: 'async' modifier cannot be used with 'abstract' modifier.
  protected abstract async handleEvent(event: KeyEvent): Promise<boolean>;
                     ~~~~~
    at https://deno.land/x/cliffy@v0.15.0/prompt/_generic_prompt.ts:65:22
```

Reference to a related discussion here: https://github.com/denoland/deno/issues/8690

**Comment by c4spar** [comment]
Hi @danjrauch,

this issue should be already fixed in v0.16.0. Let me know if you have still problems with this version.

**Comment by NoCtrlZ** [comment]
Same error here.
I am using typescript version `4.1.3`.
```
$ tsc
src/transport.ts:7:14 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.

7     abstract async request(method: string, params): Promise<any>;
               ~~~~~

src/transport.ts:14:14 - error TS1243: 'async' modifier cannot be used with 'abstract' modifier.

14     abstract async disconnect();
                ~~~~~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NoCtrlZ** [comment]
but this error didn't happen with typescript version `4.0.5`.

**Comment by c4spar** [comment]
@NoCtrlZ, sry for the late response but this is not an error from cliffy because cliffy doesnt has a file named `transport.ts`. This must come from a diferent 3rd party module.
