### ISSUE TITLE
Improve select prompt (with search)

### ISSUE THREAD

**Issue by quilicicf** [c4spar/deno-cliffy#139]
Hi, 

I've finally found the time to experiment with the select prompt with auto-complete and here is the feedback. 

## Ctrl-C keeps the console dirty

When someone ctrl-c's instead of validating the prompt, the options stay displayed and clutter the terminal. 

![Selection_057](https://user-images.githubusercontent.com/5594303/106602352-290cca00-655d-11eb-9017-3ff0695eef46.png)

If it is possible, it'd be nice to catch the SIGINT signal and cleanup. 

## Less-strict search method

The current search method shows a few improvement opportunities IMO:

* it currently only matches the values. This has the drawback that when searching in options with names, the values are not displayed and may not share a single character in common with the values (ex: `{name: 'Blue', value: '#0000AA'}`).
* is searches at the beginning of the value and not everywhere (meaning `new` does not match `Add a new feature`).

I think it would be better to search on names when provided and to use a case-insensitive-match-anywhere search method. 

Something like:

```js
function searchMethod (allOptions, searchText) {
  return allOptions
    .filter(option => !option.disabled)
    .reduce(
      (seed, option) => {
        const lowerCaseName = option.name.toLocaleLowerCase();
        const lowerCaseValue = option.value.toLocaleLowerCase();
        const lowerCaseSearch = searchText.toLocaleLowerCase();
        
        const matchesPerfectly = lowerCaseName === lowerCaseSearch || lowerCaseValue === lowerCaseSearch;
        if (matchesPerfectly) { // Put perfect match first!
          return [ option, ...seed ];
        }
        
        const matches = lowerCaseName.includes(lowerCaseSearch) || lowerCaseValue.includes(lowerCaseSearch);
        return matches ? [ ...seed, option ] : seed;
      },
      [],
    );
}
```

WDYT?

> I can help with implementation if you want to take these, and can split issues etc... :-)

**Comment by c4spar** [comment]
thx for the feedback @quilicicf!

1) normely the output should be cleaned on `ctrl+c`, if not than this is a bug. But i can not reproduce this on my mac. Which operating system and deno version do you use? And can you show me your code?

2) I was already working on a fuzzy search implementation, but it was not so easy to get this work together with autosuggestions. So i decided to add a simple solution first. But i would like to add fuzzy search before v1.0.

**Comment by quilicicf** [comment]
## Clear terminal on SIGINT

I'm using Deno 1.7.0 on Ubuntu 20.

The code is available [here](https://github.com/quilicicf/Gut/blob/master/src/commands/simple/execute.ts#L58) (nothing fancy).

I can provide a simpler reproduction code if that helps.

## Fuzzy search

As for the fuzzy search it'd be great! If I can be of any help, don't hesitate to ask :-)

**Comment by c4spar** [comment]
thx! With docker it was also working for me, but i can reproduce it on a real debian machine now. Will try to fix it.

**Comment by c4spar** [comment]
@quilicicf the issue with the stdout should be fixed now. i realized, there was realy no logic for clearing the stdout. i think, it was just my zsh and docker which cleared the stdout automatically.

**Comment by quilicicf** [comment]
Noice! 
I've tested it and it works on commit `a6b5d36` thanks :-)
