### ISSUE TITLE
Return named arguments

### ISSUE THREAD

**Issue by c4spar** [c4spar/deno-cliffy#14]
At the moment the parse method returns an object with an options object and an args array.

```typescript
const { options, args } = await new Command()
    .arguments( '<cmd:string> [env:string] [dirs...:string]' )
    .parse(Deno.args);

console.log('cmd:', args[0]);
```

The command should return an args array with named args:

```typescript
const { options, args } = await new Command()
    .arguments( '<cmd:string> [env:string] [dirs...:string]' )
    .parse(Deno.args);

console.log('cmd:', args[0]);
console.log('cmd:', args.cmd);
```

**Comment by phrohdoh** [comment]
> The command should return an args array **with named args**

That's not really an array then, is it?

If I recall correctly TypeScript recently announced support for labels for tuple items.
Is that relevant?

**Comment by c4spar** [comment]
Sry for the late response @phrohdoh.
This was just an idea. I don't think i will implement this for now. I think it's enough as it is currently and just name your variables like this:
```typescript
new Command()
  .arguments( '<cmd:string> [env:string] [dirs...:string]' )
  .action((options, cmd: string, env: string, dirs: Array<string>) => {})
  .parse()
```
or with named tuples as you mentioned:
```typescript
const { args: [cmd, env, dirs] } = new Command<{}, [cmd: string, env: string, dirs: Array<string>]>()
  .arguments( '<cmd:string> [env:string] [dirs...:string]' )
  .parse()
```
