### ISSUE TITLE
Prompt error when compiled

### ISSUE THREAD

**Issue by juliostanley** [c4spar/deno-cliffy#161]
Hi

On deno 1.8.1

The following:
- Runs with `deno run --unstable test.ts`
- Doesn't run with `deno compile -o test --unstable test.ts; ./test`

```typescript
import {
  Confirm,
  prompt,
} from "https://deno.land/x/cliffy@v0.17.2/prompt/mod.ts";
await prompt([{name:'Test',message:`Yes?`,type:Confirm}]);
```

----

The error is during execution `./test`
```
error: TypeError: Cannot read property 'map' of undefined
    at PromptList.<instance_members_initializer> (file://$deno$/bundle.js:1614:26)        
    at new PromptList (file://$deno$/bundle.js:1620:16)
    at prompt (file://$deno$/bundle.js:1606:12)
    at file://$deno$/bundle.js:1732:7
```

Haven't tried to look into it, any thoughts?

**Comment by c4spar** [comment]
Hi @juliostanley, thx for finding this issue!
Seems there is another bundle issue with deno. I have looked into it and i think i found the problematic code.

Seems `deno compile` doesnt bundle code like this correctly:

```typescript
export class Foo {
  bar = this.options.bar;
  constructor(
    protected options: { bar: string },
  ) {}
}
error: Uncaught TypeError: Cannot read property 'bar' of undefined
    bar = this.options.bar;
```

I will create a deno issue.

**Comment by c4spar** [comment]
https://github.com/denoland/deno/issues/9773

**Comment by juliostanley** [comment]
> [denoland/deno#9773](https://github.com/denoland/deno/issues/9773)

Thank  you 👍

**Comment by royletron** [comment]
@c4spar I noticed that they had merged a change to fix it so pulled the nightly build using [Deno nightly](https://deno.land/x/nightly), now I get the error:

```
error: TS2729 [ERROR]: Property 'prompts' is used before its initialization.
  private names: string[] = this.prompts.map((prompt) => prompt.name);
                                 ~~~~~~~
    at https://deno.land/x/cliffy@v0.18.0/prompt/prompt.ts:2011:34

    'prompts' is declared here.
        private prompts: PromptOptions<string, any, any>[],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/cliffy@v0.18.0/prompt/prompt.ts:2019:5
```

guessing whenever this lands it's likely to cause a lot of breaks...

**Comment by c4spar** [comment]
thx @royletron, i will deploy a fix for this!

**Comment by c4spar** [comment]
hey @juliostanley and @royletron,

i have released a new version. v0.18.1 should now work with the current deno and also with the latest nigthly version.

```typescript
import {
  Confirm,
  prompt,
} from "https://deno.land/x/cliffy@v0.18.1/prompt/mod.ts";

await prompt([{ name: 'Test', message: `Yes?`, type: Confirm }]);
```
