### ISSUE TITLE
Typo in completions help

### ISSUE THREAD

**Issue by grempe** [c4spar/deno-cliffy#174]
Is:

`For mor information...`

Should be:

`For more information`

https://github.com/c4spar/deno-cliffy/blob/717abd89d69287375990d079b72559f5d133673f/command/completions/mod.ts#L25

Also in the same file I think it should be `add the following line` instead of `add following line`

https://github.com/c4spar/deno-cliffy/blob/717abd89d69287375990d079b72559f5d133673f/command/completions/mod.ts#L19

**Comment by c4spar** [comment]
Thx! Is fixed.
