### ISSUE TITLE
prompt.ts 404

### ISSUE THREAD

**Issue by About7Sharks** [c4spar/deno-cliffy#18]
https://deno.land/x/cliffy/prompt.ts import url 404

**Comment by c4spar** [comment]
Hi @About7Sharks,
thx for the issue. You are right i forgot to commit this file. Iwill fix it.
Meanwhile you can use this entry file: https://deno.land/x/cliffy/packages/prompt/mod.ts

**Comment by c4spar** [comment]
fixed in v0.6.1
