### ISSUE TITLE
Prompts breaks on deno 1.9

### ISSUE THREAD

**Issue by sylc** [c4spar/deno-cliffy#185]
Prompt breaks in deno 1.9.0, but is working in 1.8.2
```
// ./test.ts
import { Input } from "https://deno.land/x/cliffy/prompt/mod.ts";

const name: string = await Input.prompt({
  message: `Choose a username`,
  minLength: 8,
});
```
then `deno run --unstable ./test.ts` 

works in 1.8.2
in 1.9.0
```
error: TS2729 [ERROR]: Property 'prompts' is used before its initialization.
  private names: string[] = this.prompts.map((prompt) => prompt.name);
                                 ~~~~~~~
    at https://deno.land/x/cliffy@v0.17.0/prompt/prompt.ts:2011:34

    'prompts' is declared here.
        private prompts: PromptOptions<string, any, any>[],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/cliffy@v0.17.0/prompt/prompt.ts:2019:5
```

probably an upstream issue though.

**Comment by c4spar** [comment]
Hi @sylc,

Can you try this again with the latest cliffy version? This should be already fixed.

**Comment by sylc** [comment]
Yes, i've actually just tried 
`import { Input } from "https://raw.githubusercontent.com/c4spar/deno-cliffy/v0.18.2/prompt/mod.ts";` and it works. 

I guess, I just need to understand better the caching applied by deno.

thanks for the great library BTW!
