### ISSUE TITLE
First class support for enums/choices

### ISSUE THREAD

**Issue by JohannesRudolph** [c4spar/deno-cliffy#188]
Thanks a lot for making cliffy available! Looks very promising so far. I have a CLI use case that involves many options that allow users to specify one value from a list of legal values. Based on the examples provided in the docs I was able to build myself a `Type` to handle the most common validation scenarios:

```typescript
export class EnumType extends Type<string> {
  
  constructor(private readonly allowed: readonly string[]){
    super();
}

  public parse({ label, name, value }: ITypeInfo): string {
    if (!this.allowed.includes(value)) {
      const legal = this.allowed.map(x => `"${x}"`).join(", ");

      console.error(
        `Illegal ${label.toLowerCase()} ${name}: must be one of [${legal}] but got "${value}".`,
      );
      Deno.exit(1)
    }

    return value;
  }

  public complete(): string[] {
    return this.allowed.slice();
  }
}
```

I'm using this together with a bit of typescript trickery for type-safe option parsing. 

```typescript
const ALL_FORMATS = ["json", "yaml"] as const;
type FormatsTuple = typeof ALL_FORMATS;
type Format = FormatsTuple[number];

const formatsType = new EnumType(ALL_FORMATS);

export interface ShowOpts {
  instanceId: string;
  outputFormat: Format;
  pretty: boolean;
}

// ... 

  program
    .command("show <repo>")
    .type("format", formatsType)
    .description(
      "Shows the state stored service instance stored in a UniPipe OSB git repo.",
    )
    .option(
      "-i, --instance-id <id>",
      "Service instance id.",
    )
    .option(
      "-o, --output-format <output-format>",
      "Output format. Supported formats are yaml and json.",
    )
    .option(
      "--pretty",
      "Pretty print",
    )
    .action(async (options: ShowOpts, repo: string) => {
      await show(repo, options);
    });
```

So far this seems to work very well. However I was thinking that cliffy.io already provides a lot of built-in "batteries included" options scenarios like negations, lists etc. So I wonder if you would consider adding any first-class support for enum/choice options? 

This could also tie in deeper with e.g. the default help command, for which I haven't figure out yet how to make the help text print the "legal" option values, or provide in-depth man page style help on individual option values.

**Comment by c4spar** [comment]
Hi @JohannesRudolph,

sounds good! Will definitly add more default types!
If you are interrested of making a PR to add the EnumType, this would be great! 😉. But the EnumType value should be generic, than i can infer the type to make it work with generic options.

My suggestion:

```typescript
export class EnumType<T extends string> extends Type<T> {

  constructor(private readonly allowed: ReadonlyArray<T>) {
    super();
  }

  public parse({ label, name, value, type }: ITypeInfo): T {
    if (!this.allowed.includes(value as T)) {
      const legal = this.allowed.map((x) => `"${x}"`).join(", ");

      throw new ValidationError(
        `${label} "${name}" must be of type "${type}", but got "${value}". Possible values are: ${legal}`,
      );
    }

    return value as T;
  }

  public complete(): string[] {
    return this.allowed.slice();
  }
}
```
and then:
```typescript
const formatsType = new EnumType(["json", "yaml"]);

new Command()
  .type("format", formatsType)
  .option<{
    // this is currently not working, but i can adapt the typings to map the custom type
    // to the return value of the custom type.
    outputFormat: typeof formatsType
  }>(
    "-o, --output-format <output-format:format>",
    "Output format. Supported formats are yaml and json.",
  )
  .action(async ({ outputFormat }) => {
    // ...
  });
```

We can also provide a helper type to infer the return value of a custom type, if someone don't want to use generic types.

```typescript
type TypeValue<T extends Type<unknown>> = T extends Type<infer V> ? V
  : never;
```

For the help text, I'm thinking of just displaying the return value of the complete method. But I still need to play with this a bit. Not sure if this can cause problems with custom completions.

```typescript
const formatsType = new EnumType(["json", "yaml"]);

interface Options {
  format: TypeValue<typeof formatsType>;
}

new Command()
  .type("format", formatsType)
  .option(
    "-o, --output-format <output-format:format>",
    "Output format. Supported formats are yaml and json.",
  )
  .action(async (options: Options) => {
    await show(repo, options);
  });
```

What do you think?

**Comment by JohannesRudolph** [comment]
Thanks for your feedback, I just had a quick stab at this. However I realized I'm not well versed with generic options like you showed in your example `{ format: TypeValue<typeof formatsType> }`. Also I'm a bit out of touch with advanced typescript trickery like `infer` so I guess you have a much better picture of the final result you want to aim for to keep it consistent with the rest of cliffy. 

> For the help text, I'm thinking of just displaying the return value of the complete method. But I still need to play with this a bit. Not sure if this can cause problems with custom completions.

I haven't played with the completions feature yet. The way I understand your idea is that you effectively want to treat the help text like a "complete an empty text/command" request (like you would hit autocomplete without any text before your cursor in an IDE). That sounds like a sensible choice. However, you may want to consider adding an explicit method for rendering the help text as a means of implementing separate completion/help behavior.

**Comment by c4spar** [comment]
> Thanks for your feedback, I just had a quick stab at this. However I realized I'm not well versed with generic options like you showed in your example { format: TypeValue<typeof formatsType> }. Also I'm a bit out of touch with advanced typescript trickery like infer so I guess you have a much better picture of the final result you want to aim for to keep it consistent with the rest of cliffy.

@JohannesRudolph No problem! I can add the EnumType. I'm working also on a different solution for your case, it's already available in the main branch. You can now specify an array of values or a RegExp as validator.
```ts
import { Command } from "https://raw.githubusercontent.com/c4spar/deno-cliffy/b319e64314bd0b0161f2ac57a81e22b1abb8130b/command/mod.ts";

const { options } = await new Command()
  .option(
    "-c, --color <color:string>",
    "choose a color",
    ["blue", "yellow", "red"],
  )
  .option(
    "-C, --color2 <color:string>",
    "choose a second color",
    /^(blue|yellow|red)$/,
  )
  .parse();
```
The array values and the regexp are also displayed in the help text.
```
-h, --help             - Show this help.
-c, --color  <color>   - choose a color          (Possible values: blue, yellow, red)
-C, --color2  <color>  - choose a second color   (Possible values: /^(blue|yellow|red)$/)
```

Would this solution work for you?

> I haven't played with the completions feature yet. The way I understand your idea is that you effectively want to treat the help text like a "complete an empty text/command" request (like you would hit autocomplete without any text before your cursor in an IDE). That sounds like a sensible choice. However, you may want to consider adding an explicit method for rendering the help text as a means of implementing separate completion/help behavior.

What I meant is that the Type class has a `.complete` method that returns the values used for shell completions, and these values could also be used for the help text. But I was also thinking about to add a second method.
