### ISSUE TITLE
Support common options shared between subcommands

### ISSUE THREAD

**Issue by sabberworm** [c4spar/deno-cliffy#2]
Given the following configuration:

```typescript
import { Command } from 'https://deno.land/x/cliffy@v0.4.0/command.ts';

await new Command()
    .option( '--db <database:string>', 'use given db' )
    .command( 'cmd1', new Command()
        .option( '--arg1', 'Arg 1' )
        .action( ( source: string, destination: string ) => {
            console.log( 'cmd1 called' );
        } )
    )
    .command( 'cmd2', new Command()
        .option( '--arg2', 'Arg 2' )
        .action( ( source: string, destination: string ) => {
            console.log( 'cmd2 called' );
        } )
    )
    .parse( Deno.args );
```

I would expect `--db` to become a shared option across the cmd1 and cmd2 subcommands. It seems that’s not the way cliffy handles this currently.
Instead, passing `--db` before the command name aborts with `Unknown command: cmd1`, passing it after yields `Unknown option: --db`.

**Comment by c4spar** [comment]
Thx for the issue.

At the moment shared options are not supported and in this setup `--db` would only be an option for the main command and not for the child commands. So you have to define the `--db` option for both child commands separately.

But shared options are on my list and i will implement this soon.
