### ISSUE TITLE
Disable `help` command but not `--help` option

### ISSUE THREAD

**Issue by umbopepato** [c4spar/deno-cliffy#20]
Hi @c4spar and thanks for the awesome work you're doing!

I was wondering if it's possible to disable the `help` command while keeping the `--help` option working. I'm using `BaseCommand`, manually registering the `--help` option and calling `command.help()` in the option handler, but I get

```
[ERROR:COMMAND] No help command registered.
```

I'd actually need to achieve the same result with the `completions` command, if it can be.

Thanks!

**Comment by c4spar** [comment]
Hi @umbopepato,

thx for the issue! You're right, this doesn't work atm because the help method trys to execute an registered help command. There are some parts i have to refactor and rethink.
But as workaround you can create the help command manually and call it within the action handler of the help option:

```typescript
import { BaseCommand } from 'https://deno.land/x/cliffy/command.ts';
import { HelpCommand } from 'https://deno.land/x/cliffy/packages/command/commands/help.ts';

const cmd = new BaseCommand();
const help = new HelpCommand( cmd );

await cmd
    .option( '-h, --help', 'Show help.', {
        standalone: true,
        action: () => help.show()
    } )
    .parse( Deno.args );
```

**Comment by umbopepato** [comment]
This works, thanks. I just had to move the logic inside a `BaseCommand` extension and override `getHelpCommand()` to avoid

```
[ERROR:COMMAND] No help command registered.
```

on invalid commands.
