### ISSUE TITLE
Add terminal size

### ISSUE THREAD

**Issue by leonskidev** [c4spar/deno-cliffy#205]
I was going to make a PR with a new size function of sorts for the `ansi` module but I'm not sure on a few things.

- Would it be okay to make `ansi` `--unstable` unless there's somewhere else to put it?
- How would you like the API to look for it? I was going with an interface `Size { width: number, height: number }` and `size` function (there could also be something on `tts` as well?).

I was going to use the (mostly) cross-platform technique of using CUP (move cursor) and CPR (report cursor position) to get the location.

Just wanted to get your thoughts on the matter first before I did anything, thanks.

**Comment by c4spar** [comment]
Hi @leonskidev,

not sure if i understand you correctly, do you want to add a method to ansi to change the size of the terminal or to get the size?

If you only want to get the size, there would already be a built-in deno method for that: `Deno.consoleSize(Deno.stdout)`

**Comment by leonskidev** [comment]
You know what, I never knew that thanks. It was just for getting the size. You learn something new every day.
