### ISSUE TITLE
[BUG] Using `Input` fails on `v0.19.0` without `--location`

### ISSUE THREAD

**Issue by littletof** [c4spar/deno-cliffy#208]
An error is thrown, when using the `Input` prompt with Deno `1.10.2` and without providing a `--location`.

It imports `_generic_suggestions` inside, which tries to access `localStorage` even without the location provided, which seems to throw an error for me.
https://deno.land/x/cliffy@v0.19.0/prompt/_generic_suggestions.ts#L21

Repro:
```ts
// deno run --unstable repro.ts
import { Input } from "https://deno.land/x/cliffy@v0.19.0/prompt/input.ts";

Input.prompt("It fails for Deno 1.10.2 without --location");
```

**Comment by littletof** [comment]
After some discussions on Discord ([ref](https://discord.com/channels/684898665143206084/689420767620104201/848521698033795092)) it seems like the only way to handle **optional** `localStorage` currently, is to use a `try/catch`, any other `typeof` or similar will throw an error, when `--location` was not provided.

**Comment by c4spar** [comment]
Hi @littletof, thx for creating the issue!

Yeah that's a bug and we should fix it. I think a `try/catch` should be fine.
Are you already working on a fix? I'm always happy if someone contributes to cliffy 🙂 
What do you think of adding a getter to the `GenericSuggestions` prompt like this?
```ts
protected get localStorage(): LocalStorage | null {
  // Keep support for deno < 1.10.
  if (this.settings.id && "localStorage" in window) {
    try {
      return (window as any).localStorage;
    } catch (_) {
      // Ignore error if --location is not set.
    }
  }
  return null;
}
```

**Comment by littletof** [comment]
@c4spar Seems like it would work. Will look into opening a PR later today.

**Comment by c4spar** [comment]
Cool thx 🙂
