### ISSUE TITLE
Possible for custom '?' character, or none at all?

### ISSUE THREAD

**Issue by jabza** [c4spar/deno-cliffy#221]
I couldn't find a way to modify the very first character '?'. Is there a way?
Thank you.

**Comment by c4spar** [comment]
Currently no, but I aggree, it would make sense to add a prefix and maybe also a postfix option. Will look into it.
But if you want to make a PR for adding these option feel free to do so 🙂

**Comment by jabza** [comment]
Thanks, the library is fantastic either way. Thanks for creating it!

**Comment by c4spar** [comment]
Glad you like it!
