### ISSUE TITLE
External Commands on Windows is currently broken and will throw an "os error 123"

### ISSUE THREAD

**Issue by rbeesley** [c4spar/deno-cliffy#223]
https://github.com/c4spar/deno-cliffy/blob/d93ad7d8033dd5a630e6bad05722f96392e7c54e/command/command.ts#L1038-L1039

The mainModule path on Windows is file:///[DriveLetter]. With Linux and MacOS, there would be a root '/' when writing the path, but on Windows the path would begin with the drive letter. The replace function on Windows leaves a preceding slash so the result after the replacement is "/[DriveLetter]:/foo/bar.ts". When split, this leaves an empty string for the first part.

This causes https://github.com/c4spar/deno-cliffy/blob/d93ad7d8033dd5a630e6bad05722f96392e7c54e/command/command.ts#L1075 to throw os error 123, as it is trying to source "/[DriveLetter]:/foo/bar.ts" instead of "[DriveLetter]:/foo/bar.ts".

If you drop the preceding slash like was done with [alephjs#201](https://github.com/mbdavid/aleph.js/commit/b48fd4e3a3a052e423d20ead3e3b63e45f748131), for what appears to be the same problem, I believe this will fix the issue. Meanwhile on Windows, .executable() can't be used to call an external sub command.

**Comment by rbeesley** [comment]
I've made the first change and while working on source code this seems to be working. I anticipate that there may be additional fixes necessary to make this work once compiled as stand alone. Similarly I'm not sure how this will work if `installed`. With `deno run` however, this seems to be working now but since I'm not aware of the intricacies on another OS, and I'm not sure why there was the `return false` instead of `continue`, I don't know that I'd immediately commit. If there's more work to making commands work properly on Windows, I'll consider adding them to this bug report if it hasn't been committed upstream yet.

**Comment by c4spar** [comment]
@rbeesley i made some refactorings. the sub command needs to be installed globally now and the executable will be executed directly without `deno run`.
