### ISSUE TITLE
Expose prompt integration testing functions to users (?)

### ISSUE THREAD

**Issue by WilcoKruijer** [c4spar/deno-cliffy#236]
This is a bit of a random thought, so not sure how feasible and/or useful it is. But on the surface it seems useful to me to expose some of the functions you use in Prompt's [integration tests](https://github.com/c4spar/deno-cliffy/blob/main/prompt/test/integration/test.ts) to the user. So CLIs that use your library can be thoroughly tested in the same manner. Feel free to close this issue if you do not agree.

Thanks for the framework. There is some great stuff in here!

**Comment by c4spar** [comment]
hey @WilcoKruijer,

this is definitly on my list to expose some helper functions for integration tests, but currently there are some issues with the integration tests where some test's behaves different as expected which need's to be fixed first.

Would you prefere to expose exaclty the same functions or would you preferre some different api? I'm open for any suggestions how the api could look like.
