### ISSUE TITLE
Improve colors for help text to support more terminal themes

### ISSUE THREAD

**Issue by c4spar** [c4spar/deno-cliffy#237]
As discussed in the discord channel https://discord.com/channels/748965956377772055/804514019301916693/853276012619890699 we should think about using different colors for the generated help text, because in some terminals like Powershell some parts of the help text are not or badly visible.

*legacy powershell theme*
![powershell theme](https://cdn.discordapp.com/attachments/804514019301916693/853276077387415583/Screen_Shot_2021-06-12_at_10.13.49_AM.png)

dragonstyle from the Discord channel suggested to use some rgb colors like `5DADE2` for blue and `A569BD` for purple, which are more visible than the other colors in the legacy powershell theme, and I like the colors too.

*blue on blue*
![blue on blue](https://cdn.discordapp.com/attachments/804514019301916693/853353637535154196/Screen_Shot_2021-06-12_at_3.22.07_PM.png)
*purple on blue*
![purple on blue](https://cdn.discordapp.com/attachments/804514019301916693/853353627724546078/Screen_Shot_2021-06-12_at_3.21.47_PM.png)

But the problem with rgb colors is that they can't be mapped. Most terminals have the ability to map the default ansi colors to different colors to create better terminal themes. But this is not possible when we use rgb colors.

I would prefer to stick with the default ansi colors, but it would be cool to get some more feedback from the community on what colors we should use to support a wide range of terminal themes.

**Comment by ayakovlenko** [comment]
Is it possible to disable colored output?

**Comment by eropple** [comment]
Been looking at this. Is there appetite for making Cliffy more generally themeable? I might be able to contribute if so.

**Comment by c4spar** [comment]
Hi @eropple, any help is welcome.
I think it's fine for me to make the colors configurable. Do you already have an idea how to implement this?

**Comment by c4spar** [comment]
np, thx!
