### ISSUE TITLE
Cannot use options values that starts with a `-`

### ISSUE THREAD

**Issue by lowlighter** [c4spar/deno-cliffy#247]
Consider the following: 

```ts
import { Command } from "https://deno.land/x/cliffy/command/mod.ts";

await new Command()
  .command("test", new Command()
    .option("--value <value>", "Value")
    .action(console.log)
  )
  .parse(Deno.args);
```

```
deno run test.ts test --value "-1.5"
```

```
  error: Missing value for option "--value".
```

My guess is that because the first character of value is a `-` it gets treated as an option, but it should not since it is enclosed between quotes indicating a raw string.

Escaping it with a single backslash result into the following:
```
{ value: "\\-1.5" }
```

I may be missing something, but in this case it prevents the use of negative numbers as values 😅

**Comment by c4spar** [comment]
Thx will look into it!

I noticed it is working if you use `number` as type.

```ts
await new Command()
  .command(
    "test",
    new Command()
      .option("--value <value:number>", "Value")
      .action(console.log),
  )
  .parse(Deno.args);
```

Will try to fix it for `string` and `integer` type.

**Comment by c4spar** [comment]
with `number` it is also not always working. will look into it.
