### ISSUE TITLE
version command should end with a new line

### ISSUE THREAD

**Issue by oscarotero** [c4spar/deno-cliffy#255]
Hi. First, thanks for this library!

I'm using it for Lume (a static site generator) and when I run `lume -V`, I get the following output:

<img width="281" alt="imaxe" src="https://user-images.githubusercontent.com/377873/127374075-8ce34bc3-dace-4ff9-a931-e6ee62816783.png">

I believe the `%` character at the end is because the output doesn't return a new line. It should return something like `version + "\n"`.

**Comment by c4spar** [comment]
thx will fix it.
