### ISSUE TITLE
Required env. vars

### ISSUE THREAD

**Issue by wms** [c4spar/deno-cliffy#260]
Is it possible to mark an environment variable declared through `.env()` to be required? Seems a little redundant to have to add my own explicit `Deno.env.get('SOME_VAR') !== undefined` checks.

**Comment by c4spar** [comment]
currently not but will add an `required` option.

**Comment by c4spar** [comment]
@wms required environment variables are now supported and it is now possible to get the parsed environment variables from the options object. Types can be specified the same way as the option types.
For example:
```ts
await new Command()
  .env<{ someEnvVar: boolean }>(
    "SOME_ENV_VAR=<value:number>",
    "Description ...",
    { required: true },
  )
  .action((options) => {
    console.log(options.someEnvVar);
  })
```
[Documentation](https://github.com/c4spar/deno-cliffy/tree/main/command#-environment-variables) is also updated. Will be available in the next release.
