### ISSUE TITLE
How to pass options before a sub-command ?

### ISSUE THREAD

**Issue by soootaleb** [c4spar/deno-cliffy#277]
Hello,

Thanks a lot for the cliffy work, I just started using it but I already love the method chaining approach;

However I'd like to build a CLI in a way that doesn't seem to be allowed by the framework

`abcdctl -a localhost -p 8080 chain --from source --to destination --amount 69`

My basic command abcd has several sub-commands (in this example `chain`), but the server arguments (`-a` for the addr & `-p`for the port) are global to all sub-commands

Here is my try

```
let remote: Client;

await new Command()
  .name("abctl")
  .version("1.0.0")
  .description("Interact with abcd")
  .option("-a, --address <addr>", "HTTP endpoint", { default: "localhost" })
  .option("-p, --port <port>", "HTTP port", { default: 8080 })
  .action(async ({ address, port }: { address: string; port: number }) => {
    remote = await new Client(address, port).co.catch(_ => Deno.exit(1));
    await remote?.ping().then(console.dir);
  })
  .command("chain", new Command()
    .description("Interact with blockchain")
    .version("0.1.0")
    .option("-f, --from <from:string>", "Source wallet")
    .option("-t, --to <to:string>", "Destination wallet")
    .option("-a, --amount <amount:number>", "Amount")
    .action(async ({ from, to, amount } : {
      from: string,
      to: string,
      amount: number
    }) => {
      const response = await remote.chainadd(from, to, amount);
      console.dir(response);
      Deno.exit(0)
    })
  )
  .parse(Deno.args);
```

The problem is that when I execute the example I get an error stating that the "chain" command does not exist (and it offers me to try "chain" instead)

Is my objective reachable with this framework or I must change my approach ? 

Thanks a lot

**Comment by c4spar** [comment]
Hi @soootaleb, this is actually not supported. The sub-command must be the first argument.
Why do you want to pass the options before the sub-command? what would you expect?

**Comment by soootaleb** [comment]
Hello @c4spar the arguments before the sub command are common and required by all sub commands, that’s why I’d rather see them before the sub command even if it is not a hard requirement

**Comment by paambaati** [comment]
+1 for this. I've run into this same scenario, where I declare a few common options up-front, followed by subcommand-specific actions. Type inference for those common options also does not seem to work.

**Comment by CanRau** [comment]
Yea I agree that would be super helpful.
For example in the CLI I'm building I'd like to have some global options before the subcommand and then be able to simply change the subcommand at the very end while keeping the same options, I know I can just jump before the options though it's much more convenient 😇

**Comment by c4spar** [comment]
It's now supported in v0.24.3 😉

**Comment by c4spar** [comment]
Reverted in v0.25.1 because of some issues. Will fix it in the next release.
