### ISSUE TITLE
command: Missing required arguments does not cause an error when no arguments are passed

### ISSUE THREAD

**Issue by utdemir** [c4spar/deno-cliffy#292]
In this example:

```
import { Command } from "https://deno.land/x/cliffy@v0.20.0/command/mod.ts";

const args = await new Command()
  .name("repro")
  .version("0.1.0")
  .option("--arg1 <string>", "desr1", { required: true })
  .option("--arg2 <string>", "desc2", { required: true })
  .action((opts) => {
    console.log(opts)
  })
  .parse(Deno.args);
```

If I pass `arg1`, but not `arg2`, it fails as expected:

```
$ deno run ./cli/repro.ts --arg1 foo
  Usage:   repro
  Version: 0.1.0

  Options:

    -h, --help               - Show this help.
    -V, --version            - Show the version number for this program. 
    --arg1         <string>  - desr1                                      (required)
    --arg2         <string>  - desc2                                      (required)

  error: Missing required option "--arg2".
  ```
  
 However, if I neither pass `arg1` nor `arg2`, then the parsing does not fail and the action is run:
 
 ```
$ deno run ./cli/repro.ts
{}
```

This was unexpected for me, since I would expect it to fail and never run the action without the required parameters. 

The same issue is present also when passing parameters to the subcommands.

**Comment by c4spar** [comment]
Hi @utdemir, sorry for the late reply!

Currently you need to call `.allowEmpty(false)` to throw an error if no arguments are passed. I'm not quite sure why I set the default value of allowEmpty to true. I will look into this and possibly change the default.

**Comment by utdemir** [comment]
`.allowEmpty(false)` indeed makes it behave as I expected, thank you!

>  I will look into this and possibly change the default.

I do feel like it would be a better default, but the current state also works for me. I'm leaving the issue open just as a reminder about the default, but feel free to close it if you're happy with it :).

Thanks again.
