### ISSUE TITLE
[Enhancement] Additional command properties (treated like version)

### ISSUE THREAD

**Issue by josh-hemphill** [c4spar/deno-cliffy#293]
There's often other things like major dependency versions and other critical application properties that you'd want listed next to the app version, so I'd be nice to have a simple workflow for adding that.

**Comment by c4spar** [comment]
Hi @josh-hemphill,
do you want to show the extra properties in the help text or only with the version option.

Actually you could do something like this, if you want to show the extra properties only with the long version option:

```ts
await new Command()
  .version("0.1.0")
  .versionOption("-V, --version", "Print version.", {
    action() {
      const isLong = this.getRawArgs().includes(`--version`);
      if (isLong) {
        console.log(
          `${this.getName()} ${this.getVersion()}\n` +
          `deno ${Deno.version.deno}\n` +
          `v8 ${Deno.version.v8}\n` +
          `typescript ${Deno.version.typescript}`
        );
      } else {
        console.log(this.getVersion());
      }
    }
  })
  .parse(Deno.args);
```

Maybe it makes sense to add a `.longVersion()` method to make it simpler to to somthing like this.
If you have any preferred way of doing this feel free to make a suggestion 😉

**Comment by josh-hemphill** [comment]
Hi,
Having that additional info in the `Help` text is the part that would require additional workflow or method changes.
Yeah, that's the route I went for providing that info elsewhere, but I'd like to have some of the most critical info in the help text, formatted similarly to the version, and the only way I could think to that would be to try and replace the help text and split the default help text on the version and insert the additional stuff, but that's going add some more bulky code to my entry cli file, so I was hoping that this kind use case could warrant adding something to the lib to make it cleaner and maybe similar to the version, or just extend the version method with an optional object of key/value pairs to add additional critical application properties and format them similarly to the version.

**Comment by c4spar** [comment]
hey @josh-hemphill,
i have added a new `.meta()` method which can be used to add additional information to the help output. You can test it in the `command/meta` branch: https://github.com/c4spar/deno-cliffy/blob/command/meta/command/README.md#additional-info. If you have any suggestions just let me know 😉
