### ISSUE TITLE
Input.prompt not working with Deno 1.15.3

### ISSUE THREAD

**Issue by ItaloSa** [c4spar/deno-cliffy#299]
This is the error I'm getting when trying to run the example

![image](https://user-images.githubusercontent.com/28374391/141026429-036a9abf-1cc3-4021-8110-059011b239fd.png)

![image](https://user-images.githubusercontent.com/28374391/141026413-2d3c9ba2-89f8-452f-a680-6e9815e9ba67.png)

**Comment by c4spar** [comment]
@ItaloSa you need to pass the `--unstable` flag before the file name: `deno run --unstable mod.ts`
