### ISSUE TITLE
Add an easier way to define nested subcommands.

### ISSUE THREAD

**Issue by c4spar** [c4spar/deno-cliffy#30]
It should be possible to define nested sub commands via namespaces.

```typescript
await new command()

    .command( 'command1 [arg]' )
    .description( 'First level sub command' )
    .action( console.log )

    .command( 'command1.command2 [arg]' )
    .description( 'Second level sub command' )
    .action( console.log )

    .parse();
```

**Comment by NfNitLoop** [comment]
I see this was marked as completed but I'm not able to make commands like in the code example. Is this still supported?

**Comment by roelentless** [comment]
It's not supported, you can find more here: [command()](https://github.com/c4spar/deno-cliffy/blob/main/command/command.ts#L565)

**Comment by Macil** [comment]
I was trying to find out how to define nested sub-commands and I ended up on this thread. The above link was broken, but I found a working example at https://github.com/c4spar/deno-cliffy/blob/1d5feedd72017deef8831907eec5c87f9a685085/examples/command/global_commands.ts. I'm commenting this for anyone else who ends up in this situation.
