### ISSUE TITLE
doc bug: Clicking on a link in the middle of a document page does not transition as it does when the topic bar is pressed

### ISSUE THREAD

**Issue by mochi-sann** [c4spar/deno-cliffy#303]
Clicking on the topic bar as shown in the video makes the transition, but clicking on the central topic link does not make the transition as when clicking on the topic bar

https://user-images.githubusercontent.com/44772513/143680121-a8f66b72-55d5-4592-b97a-eed4dd27ab94.mov

**Comment by c4spar** [comment]
sry for late reply but thx for reporting! this is now fixed with the new website.
