### ISSUE TITLE
Options in variadic arguments

### ISSUE THREAD

**Issue by umbopepato** [c4spar/deno-cliffy#32]
In my particular use case I'd need to accept a variable number of cli arguments (including options) unrelated to cliffy after a series of valid args, for example:

```
mycmd --myoption mysubcmd myarg other args and --options
                               |
                 cliffy args <-|-> other args
```

To do this I've been using a variadic argument in `mysubcmd `

```js
new Command()
  .command('mysubcmd [myarg] [otherArgs...]');
```

but I didn't take into account that `--options` could break it

```
[ERROR:...] Unknown option --options
```

Do you have any suggestions on how to accomplish this?

**Comment by c4spar** [comment]
Hi @umbopepato,

There is an undocumented method `useRawArgs()` which you can try to use. But it is not fully tested. `useRawArs()` disables the parsing and validation of all arguments for the command on which it was called.

Here is an example:

```typescript
import { Command } from 'https://deno.land/x/cliffy@v0.7.1/command.ts';

await new Command()
  .command('mysubcmd [myarg] [otherArgs...]')
  .useRawArgs()
  .action((options, ...args) => {
    console.log(options, args);
  })
  .parse(Deno.args);
```
```
$ deno run raw-args.ts mysubcmd myarg other args and --options
{} [ "myarg", "other", "args", "and", "--options" ]
```

**Comment by c4spar** [comment]
Another way could be to use literal arguments:
```
mycmd --myoption mysubcmd myarg -- other args and --options
                                ^--
```
All arguments after `--` will be ignored by cliffy. But at the moment the literal argument will not be passed to the action handler or returned by the `.parse()` method. I have already an issue for that #26. So you have to access Deno.args by your self to get them atm.

**Comment by umbopepato** [comment]
I was literally going to ask you if something like `useRawArgs()` existed, that's perfect! Also because I'm explicitly trying to avoid the `--` separator.

Thanks @c4spar 🙂

**Comment by c4spar** [comment]
np 🙂

**Comment by c4spar** [comment]
Hey @umbopepato,

in [v0.9.0](https://github.com/c4spar/deno-cliffy/releases/tag/v0.9.0) is now a new way to resolve your issue. You can use `.stopEarly()` instead of `.useRawArgs()`. If `stopEarly` is enabled, all arguments, starting from the first non option argument, will be interpreted as raw argument.
In contrast to `.useRawArgs()` the `--help` and `--version` option will still work.

**Comment by umbopepato** [comment]
Awesome! Thank you @c4spar
