### ISSUE TITLE
Extra garbage lines on input prompt paste (containing newline chars) in Alacritty on macOS

### ISSUE THREAD

**Issue by dshick-nydig** [c4spar/deno-cliffy#326]
mod.ts:
```ts
import {
  Input,
} from "https://deno.land/x/cliffy@v0.20.1/prompt/mod.ts";

await Input.prompt("test")
```

file.txt (notice the newline):
```plaintext
this is gonna print a lot of garbage lines on paste

```

I ran:
`cat file.txt | pbcopy`
and
`deno --unstable run mod.ts`
and then pasted into the input.

I'm using macOS 12.2.1, Alacritty, and zsh (or bash). This is not reproducible with the macOS built-in `Terminal.app`, so maybe a bug in Alacritty.

![image](https://user-images.githubusercontent.com/85501722/158203013-587d5dd2-1c46-42a2-b9ae-0772883ad356.png)

**Comment by c4spar** [comment]
@dshick-nydig thx for the report, but i cannot reproduce the issue. It works fine for me with iterm2, termanl.app and also alacritty 0.10.1 on macOS 12.0.1.

**Comment by dshick-nydig** [comment]
Hmmm, maybe something to do with my shell config. I'll close for now and see if I can't pin it down.
