### ISSUE TITLE
Issue with long "words" in renderCell of table package

### ISSUE THREAD

**Issue by creatvty** [c4spar/deno-cliffy#34]
Hello Everyone,
there is an issue with the table package where an Error is thrown if the length of a single word in the cell is longer than `maxCellWidth`. In this case `fillLength` becomes negative and an error is thrown because `.repeat` is called with a negative  count value.

https://github.com/c4spar/deno-cliffy/blob/87d1b0f9bf486ac601140147d851e7839dee557c/packages/table/lib/table.ts#L215

I assume the solution would be some kind of hard wrap if the word gets longer than `maxCellWidth`.

**Comment by c4spar** [comment]
Hi @creatvty,
thx for the issue! i will take a look.

**Comment by creatvty** [comment]
Thanks for the quick response!

**Comment by c4spar** [comment]
Hey @creatvty,
the issue should be fixed in [v0.8.2](https://github.com/c4spar/deno-cliffy/releases/tag/v0.8.2).

**Comment by creatvty** [comment]
Awesome work. Thank you :+1:
