### ISSUE TITLE
Not working compiled executable

### ISSUE THREAD

**Issue by hades3729** [c4spar/deno-cliffy#381]
![unknown-2.png](https://user-images.githubusercontent.com/89024660/168487122-3a8ea09a-cdda-48ba-81d2-601fe1f775bc.png)
I cannot launch normally the compiled executable provided by `deno compile`, even tho when I run it in my terminals project with `deno run` everything is fine.
It looks like it is because deno compile don't support dynamic imports (used in Cliffy). Is there something I can do to make a functional executable?

**Comment by c4spar** [comment]
Hi @hades3729, cliffy does not use dynmic imports and as you can see from your screenshot the error is coming from deno_figlet and not from cliffy.
And deno does not support dynamic imports in compiled executables. Here is an open tracking issue https://github.com/denoland/deno/issues/8655

There is https://github.com/mandarineorg/leaf which can add static files to the compiled binary, but I'm not sure if that works for your use case.

**Comment by c4spar** [comment]
Closing because unrelated to cliffy.
