### ISSUE TITLE
ValidationError thrown in action is not handled, does not print help

### ISSUE THREAD

**Issue by Macil** [c4spar/deno-cliffy#387]
According to https://cliffy.io/docs@v0.24.2/command/error-handling#custom-validation-errors, you can throw a ValidationError inside an action callback to get the help message to print and the process to exit with an error status, but the example code does not work. If you run the example code, you get this output instead of a help message:

```
% deno run foo.ts -c black
error: Uncaught (in promise) Error: Black is not supported.
      throw new ValidationError("Black is not supported.", { exitCode: 1 });
            ^
    at Command.fn (file:///Users/macil/Coding/deno-advent2021/foo.ts:10:13)
    at Command.execute (https://deno.land/x/cliffy@v0.24.2/command/command.ts:1275:18)
    at Command.parse (https://deno.land/x/cliffy@v0.24.2/command/command.ts:1180:21)
```

**Comment by c4spar** [comment]
thx @Macil, should be fixed now.
