### ISSUE TITLE
Allow my custom -h option to override the default help command.

### ISSUE THREAD

**Issue by avery-pierce** [c4spar/deno-cliffy#411]
When creating a command that specifies a `-h` option, an error is thrown because it conflicts with `help`.

command.ts

```typescript
import { Command } from "https://deno.land/x/cliffy@v0.24.3/command/mod.ts";

await new Command()
  .name("reverse-proxy")
  .description("A simple reverse proxy example cli.")
  .version("v1.0.0")
  .option("-p, --port <port:number>", "The port number for the local server.", {
    default: 8080,
  })
  .option("-h, --host [hostname]", "The host name for the local server.", {
    default: "localhost",
  })
  .parse();
```

Result:

```
Check file:///Users/averypierce/Projects/deno-cliffy/examples/command.ts
error: Uncaught Error: Option with name "-h" already exists.
          throw new DuplicateOptionName(name);
                ^
    at Command.option (https://deno.land/x/cliffy@v0.24.3/command/command.ts:960:17)
    at Command.registerDefaults (https://deno.land/x/cliffy@v0.24.3/command/command.ts:1333:12)
    at Command.parseCommand (https://deno.land/x/cliffy@v0.24.3/command/command.ts:1145:10)
    at Command.parse (https://deno.land/x/cliffy@v0.24.3/command/command.ts:1133:25)
    at file:///Users/averypierce/Projects/deno-cliffy/examples/command.ts:33:4
```

expected result:

My custom `-h` option overrides the default `-h` (help) option (but `--help` is still available)

**Comment by c4spar** [comment]
This is already possible with the `.helpOption()` method 😉 https://cliffy.io/docs@v0.24.2/command/help#help-option

**Comment by sigmaSd** [comment]
Currently the error looks like this 
![image](https://user-images.githubusercontent.com/22427111/236611782-17e3a1f9-f37c-4d22-8a16-f591e7b85b61.png)


It doesn't immediately come to mind whats the issue, I think special casing this , and throwing an error that explains that `-h` is already used for help might be a good idea

**Comment by c4spar** [comment]
Yeah, this is not ideal. I've already thought about removing errors like this and maybe just print a warning in some sort of development mode instead.
