### ISSUE TITLE
Assigning widths for individual columns

### ISSUE THREAD

**Issue by SheetJSDev** [c4spar/deno-cliffy#430]
Currently `minColWidth` and `maxColWidth` apply to every column in a table.  Is there a way to set the min or max width for a specific column?

**Comment by SheetJSDev** [comment]
Almost perfect 😆 

To set the max col width for column B, you would expect something like this work:

```js
table.maxColWidth(10, true); // override and set the default width to 10
table.maxColWidth([, 16], false); // only set column B width to 16
```

This sets the internal state (`getMaxColWidth`) to `[ , 16 ]` and the layout engine interprets every other column as if the max width is 0

**Comment by c4spar** [comment]
I'm not sure about this. i was thinking about adding a `Column` class and a way to define some column options and a custom renderer. Something like this:
```ts
table.minColWidth(10);
table.getCol(1).minWidth(16);
```

```ts
table.columns([{
  name: "foo",
  minWidth: 16,
  value: (value: string): colors.green(value),
}, {
  name: "bar",
  minWidth: 4,
  maxWidth: 10,
  value: (value: string): value || "-",
}]);
```
