### ISSUE TITLE
IFlags is not included as an import in Command examples

### ISSUE THREAD

**Issue by njpearman** [c4spar/deno-cliffy#44]
Hi!

First, thanks for the work on this library. I'm new to Deno and TypeScript but have found the API for this lib intuitive as it's similar to command suite libs I've used in other languages.

I got a bit stuck when I implemented an action handler though, as I wasn't sure where to find the `IFlags` type. I got to it eventually from looking through the codebase but it might be helpful to mention where to find or include that dependency in the examples and docs.

**Comment by c4spar** [comment]
Hi @njpearman,

thx for the issue!
You're right. the types are not optimal yet. i'm working on this atm.

**Comment by c4spar** [comment]
Hi @njpearman,

i have updated the documentation. You don't need to use the IFlags type, it was wrong in the documentation. You can simply use the any type. There are no types for the options object atm.

**Comment by njpearman** [comment]
Great, I'll take a look. Sorry for not acknowledging sooner; I've had a busy few days.
