### ISSUE TITLE
I want to define the prompt question externally.

### ISSUE THREAD

**Issue by akira-toriyama** [c4spar/deno-cliffy#447]
Thank you for your wonderful library😍

I would like to define a question for prompt externally.
But I get a type error. Is there a better way?

---

```ts
import {
  Input,
  prompt,
} from "https://deno.land/x/cliffy@v0.25.0/prompt/mod.ts";

type Q = Parameters<typeof prompt>;

const q: Q = [
  { name: "x", type: Input }, // type error
];

prompt(q); // type error
```

**Comment by c4spar** [comment]
Hi @akira-toriyama, I'm sorry, this is not working yet. The typings for the prompt method are not completely finished and not exported yet. I will try to improve them soon.

**Comment by akira-toriyama** [comment]
@c4spar 

Thanks for the reply.
I look forward to seeing the finished product.
I will leave the close of this issue to you.

---

This is what we are thinking of using.

https://www.hygen.io/docs/generators/#interactive-prompt

We plan to define only questions, type safe.

**Comment by akira-toriyama** [comment]
@c4spar 

Thank you 
https://github.com/bird-studio/hoipoi_capsule/blob/main/deps.ts#L3-L5
