### ISSUE TITLE
Variadic arguments not working in 0.25.0 and 0.25.1

### ISSUE THREAD

**Issue by emrul** [c4spar/deno-cliffy#455]
Hi, our CLI recently broke and I found that variadic arguments appear to no longer work. At the end of our `arguments` parameter we have `[groupNamesOrIds...:string]` and up until `0.24.3` this is correctly passed to the action handler as an array of `string`.

In 0.25.0. and 0.25.1 however this now starts being passed as a string for the first argument and any subsequent arguments appear to be ignored.

**Comment by c4spar** [comment]
Works fine for me:
```ts
await new Command()
  .arguments("[arg1:number] [...restArgs:string]")
  .action((_, arg1, ...restArgs) => {
    console.log("arg1:", arg1);
    console.log("restArgs:", restArgs);
  })
  .parse();
```
There was a breaking change in v0.25.0 which is described here: https://github.com/c4spar/deno-cliffy/releases/tag/v0.25.0

**Comment by emrul** [comment]
@c4spar - that will be it! Apologies for not checking the release notes first!

**Comment by c4spar** [comment]
No problem 😉
