### ISSUE TITLE
TypeError: Deno.setRaw is not a function

### ISSUE THREAD

**Issue by JohannesRudolph** [c4spar/deno-cliffy#458]
Deno 1.26 had a breaking change to `Deno.setRaw` https://github.com/denoland/deno/issues/15796

This breaks prompt

```
TypeError: Deno.setRaw is not a function
    at Select.#readChar (https://deno.land/x/cliffy@v0.25.1/prompt/_generic_prompt.ts:299:30)
``` 

To fix it, cliffy needs to use the new API (which is then finally intended for stabilization, yay!) described in the issue above.

**Comment by rafawalter** [comment]
Same error happening in Win7 and Win10.

Deno v1.26.0 (https://github.com/denoland/deno/releases/latest)

Easy to reproduce with `deno run --unstable https://deno.land/x/cliffy/examples/prompt/prompt_list.ts`

**Comment by rafawalter** [comment]
Fix seems to be around this line:

https://github.com/c4spar/deno-cliffy/blob/cd8d73cc7407e6126976f567060b8715fa2a0a7b/prompt/_generic_prompt.ts#L299

**Comment by c4spar** [comment]
Hi, i am already aware of this change, but there is another issue I have with typescript 4.8 that I am already working on. Will deploy a fix as soon as possible.
