### ISSUE TITLE
Cannot use select prompt on Windows

### ISSUE THREAD

**Issue by oganexon** [c4spar/deno-cliffy#47]
![image](https://user-images.githubusercontent.com/52361520/87527277-2e232e00-c68c-11ea-80f3-bdd0d542200b.png)
The prompt is frozen, pressing on directional keys does nothing

```ts
const format: string = await Select.prompt({
    message: "Config format: ",
    options: [
      { name: "YAML", value: "foo" },
      { name: "JSON", value: "bar" },
    ],
  });
```

**Comment by c4spar** [comment]
Hi @oganexon,

it seems to be impossible right now to detect arrow keys on windows. There is already a deno issue https://github.com/denoland/deno/issues/5945

**Comment by oganexon** [comment]
@c4spar It is unfortunate. 
Would it be possible to have a back-up solution under Windows, for example using the "u" up and "d" down ?

**Comment by c4spar** [comment]
@oganexon good idea! i will implement some fallback keys.

**Comment by c4spar** [comment]
@oganexon, i have added `u` and `d` as fallback keys for up and down in v0.11.2. it is also possible to change the default keys now. For example:
```typescript
const color: string = await Select.prompt( {
    message: `Pick a color`,
    options: [
        { name: 'Red', value: '#ff0000' },
        { name: 'Green', value: '#00ff00' },
        { name: 'Blue', value: '#0000ff' }
    ],
    keys: {
        previous: [ 'up', 'w' ],
        next: [ 'down', 's' ]
    }
} );
```

**Comment by oganexon** [comment]
Thank you very much, this will help us in the development of our CLI, eggs. 
The nest.land team
