### ISSUE TITLE
environment variables aren't read from the terminal (`export`)

### ISSUE THREAD

**Issue by sw-yx** [c4spar/deno-cliffy#488]
with this program

```ts
import { Command } from "https://deno.land/x/cliffy@v0.25.4/command/mod.ts";

await new Command()
  .name("sample-cli")
  .version("0.0.1")
  .env("FOO=<value:string>", "FOO", { required: true })
  .parse(Deno.args);
```

i expect that i should be able to export the env var:

```bash
export FOO=mypassword
deno run foo.ts 
```

and it should be read accordingly. however this program currently generates `error: Missing required environment variable "FOO".` despite FOO being clearly defined:

```bash
$ echo $FOO                                         
mypassword
```

**Comment by 0f-0b** [comment]
The program [needs permission](https://deno.land/manual@v1.27.0/getting_started/permissions) to read environment variables. `deno run --allow-env=FOO foo.ts` would provide access to `FOO`.

**Comment by sw-yx** [comment]
dohhh.
