### ISSUE TITLE
Select.prompt broken on 0.11.1

### ISSUE THREAD

**Issue by SRNV** [c4spar/deno-cliffy#49]
![Screenshot from 2020-07-17 17-37-14](https://user-images.githubusercontent.com/37340675/87804468-36c66080-c854-11ea-8783-af285b8619d0.png)

code:
```ts
// @ts-nocheck
import { parseFlags, OptionType, InputCLI, Confirm, Select } from './deps.ts';

class OgoneCLI {
  public static async init() {
    parseFlags(Deno.args, {
      flags: [
        {
          name: 'create',
          aliases: ['c', "create"],
          type: OptionType.STRING,
        }
      ],
      parse: (type, option, argument, value) => {
        switch(option.name) {
          case 'create':
            OgoneCLI.promptCreation(value);
          break;
        }
        return value;
      }
    });

  }
  public static async promptCreation(value: string) {
    switch(true) {
      case value && ['comp', 'component', 'c'].includes(value):
        const cssLang: string = await Select.prompt({
          messsage: 'CSS pre-processor ?',
          options: [
            { name: 'Sass', value: 'sass' },
            { name: 'Denolus', value: 'denolus' },
          ]
        });
        console.warn(cssLang);
      break;
    }
  }
}
if (import.meta.main) {
  OgoneCLI.init();
}
```

**Comment by c4spar** [comment]
Hi @SRNV,

your examle works just fine for me. I don't get this error.
Does the error also occur when you clear the deno cache?
And can you tell me which deno version and which operating system you are using?

**Comment by SRNV** [comment]
I'm on Linux with deno 1.2.0.
don't know how to clear deno cache actually

**Comment by c4spar** [comment]
Hi @SRNV,
It works for me also on linux.
The cache location on linux should be `~/.cache/deno`. To clear the cache just delete the directory.
I had to clear the deno cache several times after I upgraded to a newer deno version. Maybe it help's also in your case.

**Comment by c4spar** [comment]
@SRNV , i think the problem must be your typo in `messsage` because the line where the error is thrown is the place where the GenericPrompt prints the message but the message is undefined.

**Comment by c4spar** [comment]
@SRNV i will close the issue. if the problem still exists you can reopen it.

**Comment by SRNV** [comment]
Just saw that I give `messsage` instead of `message`
Sorry for that
Seems like ts saw nothing. Is the type of options is `any` ?

**Comment by c4spar** [comment]
no the type of the select options is not any, it's `SelectOptions`. when i execute your example with the typo i get an compiler error.
