### ISSUE TITLE
Getting a reference to the resolved command when `.throwErrors()` is used

### ISSUE THREAD

**Issue by eropple** [c4spar/deno-cliffy#498]
Hey there! I've run into a nontrivial structural error in my use of Cliffy. Because we might encounter exceptional conditions across a number of situations (a 401 error thrown as a `DOMException`, for example), I was hoping to be able to use `.throwErrors()` in Cliffy as a pathway to a global event handler. However, we'd like to show usage help when we catch an error from Cliffy in the same way that the default behavior does. We have subcommands, though, and so when we catch `ValidationError`, there's no reference to the command that had actually been called from upon which we can invoke `.showHelp()`.

Could you point me towards the best way to be able to be responsive to `CommandError`s without having to wrap every `action()` in its own error handler function?

Thanks!

**Comment by c4spar** [comment]
Hey, sry for late answer, i thought i already gave an answer.
This is currently not possible but thanks for pointing this out. I will think about a solution for this.
