### ISSUE TITLE
[Regression] ValidationError thrown in action is not handled, does not print help

### ISSUE THREAD

**Issue by Macil** [c4spar/deno-cliffy#499]
The bug previously reported and fixed in https://github.com/c4spar/deno-cliffy/issues/387 is back again. In v0.25.0, the bug is fixed, but in v0.25.1 and later versions the bug is back.

**Comment by c4spar** [comment]
Thx for reporting this issue again @Macil and sry for that. There was a missing await which is fixed now. I've also added a test to make sure the issue doesn't happen again. It will be included in the next version.
