### ISSUE TITLE
zsh completions issue with options (that do not have short codes?)

### ISSUE THREAD

**Issue by eropple** [c4spar/deno-cliffy#512]
Hey there! Running into a curious bug noted in https://github.com/render-oss/render-cli/issues/42 - it seems like zsh code completions are having issues on options that lack short options? But I am not an expert at zsh completions, so I may be wrong; I just happened to notice that deleting the first line that lacked a shortopt caused an error at the next one that also didn't have a shortopt.

We generate completions statically during Homebrew install etc., so they're not in the repository, but I've uploaded them here for reference:

https://gist.github.com/eropple/bd002c1261c6fdfcecc6d4296f63f6e2

Thanks again for Cliffy - we at Render just got a GitHub sponsorship pushed through and I'm really glad we're able to help. :pray:

**Comment by c4spar** [comment]
Hey @eropple, i think i fixed both issues, you can test it with the latest version of the main branch. Let me know if you still have issues. And thx for the sponsorship! 🙂 🙏

**Comment by eropple** [comment]
Looks good here! Thanks so much for your help!
