### ISSUE TITLE
Hint color is almost unreadable

### ISSUE THREAD

**Issue by itsdouges** [c4spar/deno-cliffy#522]
Hello! I find it very hard to read the hint color:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/6801309/208788167-66ef8be2-ad6f-4d12-831c-738ba2a82a6e.png">

Is it possible to change it to a lighter color/more visible value? Can it be configured?

Love your library! I've been using it to write https://deno.land/x/deno_changesets

**Comment by itsdouges** [comment]
Ah, duplicate of https://github.com/c4spar/deno-cliffy/issues/237

I'll close this one.

**Comment by c4spar** [comment]
Not realy a duplicate since #237 is related to the command module.

I will reopen it and try a different color for the hint.

I also thought about adding a theme option to make it posible to customize all colors like this:

```ts
const theme = {
  hint: colors.brightBlue.italic,
  // ...
};

await Input.promt({
  message: "Select a module",
  theme,
});
```

The theme can be then re-used for all prompts.
