### ISSUE TITLE
Access literal inside a subcommand action

### ISSUE THREAD

**Issue by sigmaSd** [c4spar/deno-cliffy#536]
```ts
    const cliffy = await new Command()
      .command("run", "run a binary")
      .arguments("<name:string>")
      .action((opts,args) => {
        // I want to acess cliffy.literal here
      })
      .parse(Deno.args);
    console.log(cliffy.literal);
```

The example wants to run an external binary when a subcommand is called, and I want to pass the literal to it , so 
`myapp run somebin -- 1 -2 ` I can pass `1 and -2` to it

**Comment by c4spar** [comment]
Hi @sigmaSd,

you can use `.getLiteralArgs()` method of the command class for this. I think it's not documented yet.

```ts
.action(function () {
  console.log(this.getLiteralArgs());
})
```

You can also take a look at the `.stopEarly()` method: https://cliffy.io/docs@v0.25.7/command/commands#stop-early
With this you don't need the `--` to separate you options and the options of the external binary, instead `somebin` would be the separator:
`myapp run <run options> somebin <somebin options>`
All options before somebin will be parsed as `run` options and all options and arguments after `somebin` will be passed to the args array as raw arguments without validation.

**Comment by sigmaSd** [comment]
hello, 

thanks that works!
