### ISSUE TITLE
Incorrect validation error when parsing global flags mixed with sub-command flags

### ISSUE THREAD

**Issue by aleccool213** [c4spar/deno-cliffy#545]
Thanks for the making this library! 

I am trying to upgrade to the highest version as that is needed to run on newer versions of Deno. I noticed a bug in our cli app and found a way to reproduce it. It seems like when you declare sub-commands.

```typescript
// OLD CLIFFY VERSION: v0.20.1
import * as CliffyOld from "https://deno.land/x/cliffy@v0.20.1/command/mod.ts";

// create a command which has global options
const cliOld = new CliffyOld.Command()
  .name("mycli")
  .description("My CLI")
  .version("0.0.1")
  .option("-c, --config <config:string>", "Config file path.", {
    global: true,
    default: "default-file-path",
  })
  .option("-q, --quiet", "Enable quiet mode.", {
    global: true,
    default: false,
  });

// create a sub-command
const subCommandOld = new CliffyOld.Command<any>()
  .command(
    "pull-secrets",
  );

subCommandOld.option("-e, --env <env:string>", "Environment.", {
  global: false,
});

// create a sub-command of a sub-command
cliOld.command("secret-manager", subCommandOld);

// parse the command line
const oldCliffyParsedArguments = await cliOld.parse(Deno.args);

// print the parsed command line
console.log({
  options: oldCliffyParsedArguments.options,
  args: oldCliffyParsedArguments.args,
});

// NEW CLIFFY VERSION: v0.25.7
import * as CliffyNew from "https://deno.land/x/cliffy@v0.25.7/command/mod.ts";

// create a command which has global options
const cliNew = new CliffyNew.Command<any>()
  .name("mycli")
  .description("My CLI")
  .version("0.0.1")
  .option("-c, --config <config:string>", "Config file path.", {
    global: true,
    default: "default-file-path",
  })
  .option("-q, --quiet", "Enable quiet mode.", {
    global: true,
    default: false,
  });

// create a sub-command
const subCommandNew = new CliffyNew.Command<any>();

subCommandNew.command(
  "pull-secrets",
);

subCommandNew.option("-e, --env <env:string>", "Environment.", {
  global: false,
});

// create a sub-command of a sub-command
cliNew.command("secret-manager", subCommandNew);

// parse the command line
const newCliffyParsedArguments = await cliNew.parse(Deno.args);

// print the parsed command line
console.log({
  options: newCliffyParsedArguments.options,
  args: newCliffyParsedArguments.args,
});
```

Version of Deno:

```
deno 1.30.2
```

Command:

```bash
deno run src/bug.ts secret-manager pull-secrets --quiet --env test --config filepath
```

Output:

```

  Usage:   mycli secret-manager pull-secrets
  Version: 0.0.1                            

  Options:

    -h, --help              - Show this help.                                   
    -c, --config  <config>  - Config file path.   (Default: "default-file-path")
    -q, --quiet             - Enable quiet mode.  (Default: false)              
    -e, --env     <env>     - Environment.                                      

  error: Option "--config" can only occur once, but was found several times
```

(odd) workarounds which make it work:

- changing the command names to not have a dash, `secret pull`
- only using global flags before sub-command flags

Screenshot of the code where the error occurs:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/6475934/218372945-9c7ad381-ab9d-4949-ab57-ea77473285a9.png">

I might be able to help with this if pointed in the right direction, thanks!

**Comment by c4spar** [comment]
Hi @aleccool213, thx for pointing this out!
I think this can be either a bug in the flags parser or in the`parseCommand` method of the command class https://github.com/c4spar/deno-cliffy/blob/v0.25.7/command/command.ts#L1590-L1623

**Comment by c4spar** [comment]
Looks like the issue is the default value. If i remove the default value it works.

The `parseGlobalOptionsAndEnvVars` method is setting the default value for the config option (https://github.com/c4spar/deno-cliffy/blob/v0.25.7/command/command.ts#L1605) and the `parseOptionsAndEnvVars` parses the config option and fails because the default value is alrady set (https://github.com/c4spar/deno-cliffy/blob/v0.25.7/command/command.ts#L1620).

I think the `parseGlobalOptionsAndEnvVars` should not set any default values, this should be only done by the `parseOptionsAndEnvVars` method.

**Comment by c4spar** [comment]
hm i think this also doesnt work if i have a command like this `deno run example.ts --global-opt sub-command --other-opt`. Than the default values for the global options of the main command are not applied.
Currently not quite sure how to fix this.

**Comment by aleccool213** [comment]
Quite close to getting this figured out, re-implementing the duplicate option error into a standalone function which is helping, I will have time next friday to continue. Here is my wip branch: https://github.com/c4spar/deno-cliffy/compare/main...aleccool213:bugfix/545?expand=1

**Comment by c4spar** [comment]
Cool, thx for looking into it @aleccool213! I had a quick look and i think i found an easier solution.
We could add a `defaults` property to the `ParseFlagsContext` interface and then adapt following lines:

- https://github.com/c4spar/deno-cliffy/blob/v0.25.7/flags/_validate_flags.ts#L109:
  ```diff
  - defaultValues[option.name] = true;
  + ctx.defaults[option.name] = true;
  ```
- https://github.com/c4spar/deno-cliffy/blob/v0.25.7/flags/flags.ts#L227
  ```diff
  - } else if (!option.collect) {
  + } else if (!option.collect && !ctx.defaults[propName]) {
  ```

But with both solutions we have the problem that the default value handler is executed but it shouldn't. But as first pass i think it would be good enough.

A better solution could be to adapt this check so the default value is not assigned: https://github.com/c4spar/deno-cliffy/blob/v0.25.7/flags/_validate_flags.ts#L100-L105 to somthing like this.

```diff
  const hasDefaultValue: boolean = (!opts.ignoreDefaults ||
    typeof opts.ignoreDefaults[name] === "undefined") &&
    typeof ctx.flags[name] === "undefined" && (
      typeof option.default !== "undefined" ||
      typeof defaultValue !== "undefined"
-  );
+  ) &&
+  option.flags.every((flag) => !ctx.unknown.includes(flag));
``` 

But this solution is not good enough, it checks also values and ignores stopEarly and stopOnUnknown. It would require a more complicated check which could also slow down the parser.

**Comment by aleccool213** [comment]
@c4spar 

Interesting. Seems like there are multiple ways to approach this problem.

I have some time Friday to take another stab at this but it seems you have more context when it comes to your solution. If you want to fix this and steal my unit test, let me know 👍

**Comment by c4spar** [comment]
@aleccool213 you are welcome to work on it, if you need help just ping me. Otherwise i can do it later. Currently looking into some other issue.

**Comment by aleccool213** [comment]
Hey @c4spar , I got your solution working 👍 

Check out the pull request:

https://github.com/c4spar/deno-cliffy/pull/548

**Comment by c4spar** [comment]
Awesome, thx @aleccool213! I will have a look.
