### ISSUE TITLE
bug: version number is not printed using `-v`

### ISSUE THREAD

**Issue by KnorpelSenf** [c4spar/deno-cliffy#546]
When I run the CLI using `-v`, I expect it to behave the same way as when I pass `--version`. This is not the case.

```ts
// cli.ts
import { Command } from "https://deno.land/x/cliffy@v0.25.7/command/mod.ts";

await new Command()
  .name("sitemap")
  .version("0.1.0")
  .description("demo")
  .parse(Deno.args);
```

This works:
```sh
$ deno run cli.ts --version
sitemap 0.1.0
```

However, the option `-v` is not recognised:

```sh
$ deno run cli.ts -v

  Usage:   sitemap
  Version: 0.1.0  

  Description:

    demo

  Options:

    -h, --help     - Show this help.                            
    -V, --version  - Show the version number for this program.  

  error: Unknown option "-v". Did you mean option "-h"?
```

**Comment by jdahlborg** [comment]
It doesn't work with a capital V. Try a small one and it will work

**Comment by c4spar** [comment]
Exactly, cliffy uses capilatized `V` for the version option. Try `deno run cli.ts -V`.
It's also possible to change it to lowercase with the `.versionOption()` method, see https://cliffy.io/docs@v0.25.7/command/help#customize-version-option.

**Comment by KnorpelSenf** [comment]
Oh, I did not even notice that, sorry. What's the rationale behind this? :)

**Comment by c4spar** [comment]
Np 🙂 I prefer to use `-v` for verbose and `-V` for version option and I think many other cli's do the same, including the deno cli which is built with clap a rust framework which also uses `-V` by default.

**Comment by KnorpelSenf** [comment]
I see, that makes sense. Gonna get used to that now, thanks for elaborating

**Comment by KnorpelSenf** [comment]
@c4spar in https://github.com/denoland/deno/releases/tag/v1.44.0, the Deno CLI added support for lowercase `-v` via https://github.com/denoland/deno/pull/23750. Would you consider adding an option to cliffy that adds support for `-v`, as well? It could either be opt-in or opt-out. That way, you can keep using `-v` for verbose.

> Gonna get used to that now

Didn't happen yet, even though I also use a few more CLIs that do this now

**Comment by KnorpelSenf** [comment]
I am dumb, that option already exists, please ignore me
