### ISSUE TITLE
Feedback wanted: Default prompt output to stderr

### ISSUE THREAD

**Issue by c4spar** [c4spar/deno-cliffy#552]
There is a feature request and PR #419 to change the output of the prompt module from stdout to stderr but I'm not sure if this is a good default. The advantage of this would be that more cli support pipes by default.

But before I accept this request, I'd like to hear more feedback from more people about which default they prefer.
I will also open a separate PR to make the output stream configurable.

**Comment by martsokha** [comment]
Strongly against. CLI messages are not all error output.

**Comment by c4spar** [comment]
yeah i still think the same that stdout is the better default. I have made it configurable now and I will keep stdout as default.
Thx for your feedback @martsokha!
