### ISSUE TITLE
Default validator/transform fail on Checkbox prompt with numeric or non-string values

### ISSUE THREAD

**Issue by mdixon4** [c4spar/deno-cliffy#562]
The checkbox prompt expects the `value` of each option to be a string. However there exists many reasons for preferring a number or other non-string value. However, the default verifier will always return false, and if that is worked around, the default transform will throw an error.

For example, consider this code:

```js
import { Checkbox } from 'https://deno.land/x/cliffy@v0.25.7/prompt/checkbox.ts'

await Checkbox.prompt({
  message: 'Options where the value is not a string is not supported',
  options: [
    { name: 'foo', value: 1 },
    { name: 'bar', value: 2 },
  ],
})
```

If any options are selected, the user is shown "Invalid Answer". 

A custom validator can be supplied:

```js
import { Checkbox } from 'https://deno.land/x/cliffy@v0.25.7/prompt/checkbox.ts'

await Checkbox.prompt({
  message: 'Options where the value is not a string is not supported',
  options: [
    { name: 'foo', value: 1 },
    { name: 'bar', value: 2 },
  ],
  validate: _ => true,
})
```

Validation passes, but then an error is thrown: Uncaught (in promise) TypeError: val.trim is not a function

Providing a custom transform function will avoid this:

```js
import { Checkbox } from 'https://deno.land/x/cliffy@v0.25.7/prompt/checkbox.ts'

await Checkbox.prompt({
  message: 'Options where the value is not a string is not supported',
  options: [
    { name: 'foo', value: 1 },
    { name: 'bar', value: 2 },
  ],
  validate: _ => true,
  transform: _ => _,
})
```

This works.

I would be happy to contribute a pull request addressing this issue if you like.

**Comment by c4spar** [comment]
Hi @mdixon4, yes I am aware of this and I want to fix this before v1. A PR would be very welcome!
