### ISSUE TITLE
v0.12.1 Not Available on deno.land

### ISSUE THREAD

**Issue by nakleiderer** [c4spar/deno-cliffy#58]
I'm currently getting a 404 when trying to retrieve v0.12.1 from deno land. However, v0.12.0 is available. Did the Deno webhook fail while notifying Deno of the new tag?

Available: https://deno.land/x/cliffy@v0.12.1
Not Found: https://deno.land/x/cliffy@v0.12.1

```
> deno run https://deno.land/x/cliffy@v0.12.1/command.ts
Download https://deno.land/x/cliffy@v0.12.1/command.ts
error: Import 'https://deno.land/x/cliffy@v0.12.1/command.ts' failed: 404 Not Found
```

**Comment by c4spar** [comment]
Hi @nakleiderer,
yes, you are right, I didn't know that denoland has released a new registry with webhook integration.
I have added the webhook and v0.12.1 is now available on deno land.
Thanks for the information!
