### ISSUE TITLE
disallow generating completions if name is not set

### ISSUE THREAD

**Issue by sigmaSd** [c4spar/deno-cliffy#586]
If name is not set, completions will use the place holder COMMAND, 
```fish
!/usr/bin/env fish
# fish completion support for COMMAND

function __fish_COMMAND_using_command
...
```

Maybe its better to throw an error in this case letting the user know that they should set .name

**Comment by c4spar** [comment]
Would you prefere to throw an error in general if no command name is set, or only for the completions command?

**Comment by sigmaSd** [comment]
Not sure really, in practice I only noticed this with completion
