### ISSUE TITLE
Checkbox prompt thinks there's a group when there isn't

### ISSUE THREAD

**Issue by KasMA1990** [c4spar/deno-cliffy#642]
Thanks for getting the prompt grouping out 🥳 I'm using it now, and I'm very happy with it, but I've found a bug.

To reproduce, run the following example:
```ts
import { Checkbox } from "https://deno.land/x/cliffy@v1.0.0-rc.2/prompt/checkbox.ts";

const colors: string[] = await Checkbox.prompt({
  message: "Pick a color",
  options: [
    { name: "Red", value: "#ff0000" },
  ],
});
```

When running it, select the given option with space, and then hit Enter to confirm. When hitting Enter, see that this message appears:
<img width="555" alt="image" src="https://github.com/c4spar/deno-cliffy/assets/6695040/48054fcb-3415-4c48-9568-3c5a04c3ad97">

This indicates the code thinks there is a group here, even though there isn't.

**Comment by c4spar** [comment]
Thx for pointing this out. I have corrected the info message in #643.
