### ISSUE TITLE
Navigating back on the outer most prompt level can select a disabled item

### ISSUE THREAD

**Issue by KasMA1990** [c4spar/deno-cliffy#645]
To reproduce, run the following example:

```ts
import { Checkbox } from "https://deno.land/x/cliffy@v1.0.0-rc.2/prompt/checkbox.ts";

const colors: string[] = await Checkbox.prompt({
  message: "Pick a color",
  options: [
    { name: "Red", value: "#ff0000", disabled: true },
    { name: "Red2", value: "#ff0020" },
  ],
});
```

Hit the left arrow button to move to the top of the list, and see that the disabled `Red` item becomes selected.

<img width="354" alt="image" src="https://github.com/c4spar/deno-cliffy/assets/6695040/dab60f36-a375-4f39-be46-6de71ed3dcf9">

**Comment by c4spar** [comment]
thx! fixed in #646.
