### ISSUE TITLE
Standalone options does not trigger command action

### ISSUE THREAD

**Issue by sylc** [c4spar/deno-cliffy#653]
Consider the below:

```ts
import { Command } from "https://deno.land/x/cliffy@v1.0.0-rc.2/command/mod.ts";
// import { Command } from "https://deno.land/x/cliffy@v0.25.6/command/mod.ts";

await new Command()
  .name("cliffy")
  .version("0.1.0")
  .description("Command line framework for Deno")
  .arguments("<...some_args>")
  .option(
    "--foo",
    "foo option",
    {
      standalone: true,
    },
  )
  .action((_opts, ...some_args) => {
    console.log("Hello", some_args);
  })
  .parse(Deno.args);

```
execute with `deno run -A test.ts --foo`
- with `v1.0.0-rc.2`, I get no output.
- with `v0.25.6`, I get "Hello []"

My expectation is that: If a standalone option does not have an action defined then the main handler is called, as per the behaviour of `v0.25.6`
I cannot see any mention in the changelog, so i'm assuming it is a regression ?

Thanks for the great library!

**Comment by c4spar** [comment]
For standalone options you can use the action handler of the defined option. The main action handler is not executed for standalone options because otherwise it would be triggered for options like the help option as well.

Here is an updated example:

```ts
import { Command } from "https://deno.land/x/cliffy@v1.0.0-rc.2/command/mod.ts";

await new Command()
  .name("cliffy")
  .version("0.1.0")
  .description("Command line framework for Deno")
  .arguments("<...some_args>")
  .option(
    "--foo",
    "foo option",
    {
      standalone: true,
      action: (_opts, ...some_args) => {
        console.log("Foo", some_args);
      },
    },
  )
  .action((_opts, ...some_args) => {
    console.log("Hello", some_args);
  })
  .parse(Deno.args);
```

**Comment by c4spar** [comment]
Sry, I noticed that I did not read your post correctly. I was not aware that this was possible in v0.25.6. If this was possible, then it was a bug and I fixed it without realizing it. But after thinking about it, it might actually make sense to allow this.
It looks like the change was in 1.0.0-rc.1, I think it would be fine for me to reintroduce this.

**Comment by sylc** [comment]
If the current behaviour is kept, then I think, the action parameter should be made required if standalone is true, otherwise a standalone option can possibly do nothing, which could trip/surprise a developer.

I agree with you that the behaviour from `v0.25.6` make more sense. It allows more flexibility for the user to structure the code by either defining the behaviour in the specific handler or via the main action, which, in one of my use cases, I prefer. 
For the help option, from my point of view, it is still consistent with the logic of `If a standalone option does not have an action defined, then the main handler is called` because I'm expecting that, under the hood the help option has a dedicated baked-in action that made the help print something nice. (If i was to not use the baked in help but code it myself using the options, that's how i will do it)

thanks for looking into it.
