### ISSUE TITLE
Feedback on grouped select prompt

### ISSUE THREAD

**Issue by KasMA1990** [c4spar/deno-cliffy#658]
I've been using the grouped select prompts for a little while now, and I'm very happy with them. The only thing I've noticed that feels "off" is that I use the arrow keys a lot for navigating between groups (right to go in, left to go out), and when I enter a group, it is the first item of the group that is selected, and not the "Back" button. This means I press right arrow once to enter a group, and left arrow twice to exit the group again. But usually when navigating tree structures like this (e.g. file overviews), my experience is that it should be one press to exit instead of two. So the current setup is really messing with my muscle memory on that front.

I don't know if that should be enough to make a change here, but do with it what you want 😊

**Comment by c4spar** [comment]
I think i agree with you, fine for me to change this.
