### ISSUE TITLE
Is the project alive ?

### ISSUE THREAD

**Issue by rubenfiszel** [c4spar/deno-cliffy#675]
Hi,

This library is used for the windmill.dev CLI client. I see that there is less activity and releases recently (and that we're still on an rc3). Do you suggest migrating to another library for production use?

**Comment by c4spar** [comment]
Yes it is! But I had less time to maintain this project last year because I had a lot to do privately. I am currently traveling but will be back in a few days, then I will start preparing the v1 release.

**Comment by rubenfiszel** [comment]
Glad to hear!
