### ISSUE TITLE
Not available on jsr.io

### ISSUE THREAD

**Issue by Hexagon** [c4spar/deno-cliffy#680]
Would be awesome!

**Comment by RuiNtD** [comment]
I took a quick look at your deps. Looks like you only use `std` and `sinon` via skypack. `std` is [already on JSR](https://jsr.io/@std) and `sinon` can be accessed with `npm:sinon`, but may need some additional testing. Deno has made [a tool and guide](https://jsr.io/docs/migrate-x-to-jsr) for migrating to JSR, so you might want to give that a look ahead of releasing 1.0.

**Comment by andrewthauer** [comment]
#679

**Comment by timharek** [comment]
The v1.0.0-rc.4 is available on JSR now:

https://jsr.io/@cliffy

**Comment by maheshbansod** [comment]
@timharek how do i use it with jsr?
I get this when I run `deno add @cliffy/command`
```
error: jsr:@cliffy/command was not found.
```
Also this page https://jsr.io/@cliffy/command says
```
This package has not published a stable release yet.
```
I see that the version is visible in the versions tab. Are there plans to publish it soon if that's whats required to make `deno add` work? if not, is there a way to use unpublished version?
thanks

**Comment by dahlia** [comment]
@maheshbansod Try `deno add @cliffy/command@1.0.0-rc.4`?

**Comment by andykais** [comment]
I think this can be closed. This works fine for me:
```ts
import * as cliffy from 'jsr:@cliffy/command@1.0.0-rc.4'
```
