### ISSUE TITLE
@cliffy/internal isn't internal

### ISSUE THREAD

**Issue by lionel-rowe** [c4spar/deno-cliffy#730]
I'm guessing `@cliffy/internal` shouldn't be visible on JSR?

![image](https://github.com/user-attachments/assets/504f0c1a-5d62-4670-9c60-6d459adceedc)

https://github.com/c4spar/deno-cliffy/blob/33b01f838f5cf84cac86d271b0b4c00311bef0de/internal/deno.json#L4-L20

**Comment by c4spar** [comment]
Is there a way to hide it on jsr?

**Comment by lionel-rowe** [comment]
> Is there a way to hide it on jsr?

Not including `exports` in the per-directory `deno.json`. But maybe that prevents it from working as a common dependency for the various other packages? If there's no good fix then I'll just close this.

**Comment by c4spar** [comment]
I don't think there is a solution rn.
