### ISSUE TITLE
cliffy.io has broken examples

### ISSUE THREAD

**Issue by cscheid** [c4spar/deno-cliffy#743]
<img width="939" alt="image" src="https://github.com/user-attachments/assets/cf622756-a9fe-46e7-b20c-1e585b50fb71">

```
$ deno run --allow-net=localhost:8080,deno.land https://deno.land/x/cliffy@v1.0.0-rc.5/examples/command.ts
error: Module not found "https://deno.land/x/cliffy@v1.0.0-rc.5/examples/command.ts".
```

<img width="959" alt="image" src="https://github.com/user-attachments/assets/520a11b2-919c-43dc-8198-fc2635c4dbbc">

```
$ deno
Deno 1.46.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import { Command } from "https://deno.land/x/cliffy@v1.0.0-rc.5/command/mod.ts";
Uncaught TypeError: Module not found "https://deno.land/x/cliffy@v1.0.0-rc.5/command/mod.ts".
```

**Comment by c4spar** [comment]
cliffy has been published on jsr since rc.5, but it looks like I forgot to remove the deno.land webhook and accidentally kept publishing it on deno.land. the website will be updated soon.

**Comment by LazerJesus** [comment]
@c4spar hey, is there a issue i can follow to get updates on this? 
i am on deno 2.
importing from ./import_map.json is not possible. i have to import from `import { Command } from "jsr:@cliffy/command@1.0.0-rc.7";`
