### ISSUE TITLE
@-scoped imports broken in 1.0.0-rc5+

### ISSUE THREAD

**Issue by djradon** [c4spar/deno-cliffy#763]
error: Relative import path "@cliffy/internal/runtime/get-env" not prefixed with / or ./ or ../
    at https://deno.land/x/cliffy@v1.0.0-rc.7/command/command.ts:43:24

I've tried this on WSL and ubuntu 24.04 using some demo code from the Cliffy docs:

`
import { Command } from "https://deno.land/x/cliffy@v1.0.0-rc.7/command/mod.ts";

await new Command()
  // Main command.
  .name("cliffy")
  .version("0.1.0")
  .description("Command line framework for Deno")
  .globalOption("-d, --debug", "Enable debug output.")
  .action((options, ...args) => console.log("Main command called."))
  // Child command 1.
  .command("foo", "Foo sub-command.")
  .option("-f, --foo", "Foo option.")
  .arguments("<value:string>")
  .action((options, ...args) => console.log("Foo command called."))
  // Child command 2.
  .command("bar", "Bar sub-command.")
  .option("-b, --bar", "Bar option.")
  .arguments("<input:string> [output:string]")
  .action((options, ...args) => console.log("Bar command called."))
  .parse(Deno.args);
`

It works in rc4. in rc5 the error is "error: Module not found "https://deno.land/x/cliffy@v1.0.0-rc.5/command/mod.ts".

**Comment by c4spar** [comment]
cliffy is now published on jsr since rc.5. but i forgot to remove the webhook and published rc.6 and rc.7 again on deno.land.

So, for versions `<= rc.4` use deno.land and for versions `>= rc.5` use jsr.

**Comment by johnnydecimal** [comment]
The home page examples are broken.

`deno run --allow-net=localhost:8080,deno.land https://deno.land/x/cliffy@v1.0.0-rc.7/examples/command.ts` results in this error.
